name: Sonar Scan

on:
    push:
        branches:
            - main 

jobs:
    build-and-analyze:
        runs-on: [ ubuntu-latest ]
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Java
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin'
                java-version: '17'
          - name: Build Project
            run: mvn clean install -DskipTests      
          
          - name: SonarQube Scan
            uses: sonarsource/sonarqube-scan-action@master # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              SONAR_HOST_URL: 'https://sonarcloud.io/' 



